language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx
gemfile:
  - travis/ar31.gemfile
  - travis/ar32.gemfile
  - travis/ar40.gemfile
  - travis/ar41.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: travis/ar40.gemfile
    - rvm: jruby-18mode
      gemfile: travis/ar40.gemfile
    - rvm: 1.8.7
      gemfile: travis/ar41.gemfile
    - rvm: jruby-18mode
      gemfile: travis/ar41.gemfile
before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libproj-dev
